---
title: "Index"
author: "Marijn Oude Groeneger"
date: "2024-02-21"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    orientation: rows
    social: menu
    source: embed
---

```{r setup_main, include=FALSE}

library(tidyverse)
library(spotifyr)
library(ggplot2)
library(plotly)
library(compmus)
```


Introduction
================================================
```{r Introduction, child = 'introduction.Rmd'}
```

Dancing to the Beatles compared to my corpus
================================================

```{r Dance, child = 'corpus_beatles_dance.Rmd'}
```

Does Polyphia make Light work, or rather LIT?
================================================
```{r Polyphia Chromagrams, child = 'polyphia_chromagrams.Rmd'}
```

A math rock classic's self similarity
================================================
```{r Frozen Twilight SSM, child = 'frozen_twilight.Rmd'}
```

Camp Adventure tempograms
=================================================
```{r Camp Adventure, child = 'camp_adventure.Rmd'}
```

Rhythmic Complexity Analyses
=================================================
```{r Rhythmic Complexity Analyses, child = 'tempo.Rmd'}
```


